<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Partcounter</AssemblyName>
    <RootNamespace>Partcounter</RootNamespace>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.1</FileVersion>
    <InformationalVersion>0.1.0-r001</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
  </ItemGroup>
</Project>
