<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Partcounter</AssemblyName>
    <RootNamespace>Partcounter</RootNamespace>
    <Version>0.1.13</Version>
    <FileVersion>0.1.13.0</FileVersion>
    <InformationalVersion>0.1.13-r001.13-company-logo</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
